# Generated by Django 3.1.2 on 2020-12-08 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finances", "0002_auto_20201208_0156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
