# Generated by Django 3.1.2 on 2020-12-08 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finances", "0003_auto_20201208_0202"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_profile",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
