# Generated by Django 3.1.2 on 2021-01-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0005_auto_20201216_0253"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="interest_type",
            field=models.CharField(
                choices=[
                    ("Fixed", "Fixed Interest Rate"),
                    ("Variable", "Variable Interest Rate"),
                ],
                default="Fixed",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                choices=[
                    ("Credit Card", "Credit Card Loan"),
                    ("Line of Credit", "Line Of Credit"),
                    ("Student Loan", "Student Loan"),
                    ("Student Line of Credit", "Student Line of Credit"),
                    ("Personal Loan", "Personal Loan"),
                ],
                default="Personal Loan",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="end_date",
            field=models.DateField(null=True, verbose_name="Final Payment Month"),
        ),
    ]
