# Generated by Django 3.1.2 on 2021-02-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0010_auto_20210202_0635"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="current_monthly_contribution",
            field=models.FloatField(default=0, verbose_name="Current Monthly Payment"),
        ),
        migrations.AddField(
            model_name="investment",
            name="minimum_monthly_payment",
            field=models.FloatField(default=0, verbose_name="Minimum Monthly Payment"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                choices=[
                    ("Credit Card", "Credit Card Loan"),
                    ("Line of Credit", "Line Of Credit"),
                    ("Student Loan", "Student Loan"),
                    ("Student Line of Credit", "Student Line of Credit"),
                    ("Personal Loan", "Personal Loan"),
                    ("Car Loan", "Car Loan"),
                ],
                default="Personal Loan",
                max_length=50,
            ),
        ),
    ]
