# Generated by Django 3.1.2 on 2021-02-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0015_auto_20210216_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='current_monthly_contribution',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='minimum_monthly_payment',
        ),
        migrations.AddField(
            model_name='investment',
            name='expected_roi',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Expected Return On Investment'),
        ),
        migrations.AddField(
            model_name='investment',
            name='expected_volatility',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Expected Volatility'),
        ),
        migrations.AddField(
            model_name='investment',
            name='interest_type',
            field=models.CharField(blank=True, choices=[('Mutual Fund', 'Mutual Fund'), ('ETF', 'Exchange Traded Fund'), ('GIC', 'Guaranteed Investment Certificate'), ('Term Deposit', 'Term Deposit'), ('Stock', 'Stock'), ('Bond', 'Bond'), ('Cash', 'Cash')], default=None, max_length=50, null=True, verbose_name='Investment Type'),
        ),
        migrations.AddField(
            model_name='investment',
            name='investment_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Maturity Date'),
        ),
        migrations.AddField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('Mutual Fund', 'Mutual Fund'), ('ETF', 'Exchange Traded Fund'), ('GIC', 'Guaranteed Investment Certificate'), ('Term Deposit', 'Term Deposit'), ('Stock', 'Stock'), ('Bond', 'Bond'), ('Cash', 'Cash')], default='Mutual Fund', max_length=50, verbose_name='Risk Type'),
        ),
        migrations.AddField(
            model_name='investment',
            name='maturity_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Maturity Date'),
        ),
        migrations.AddField(
            model_name='investment',
            name='pre_authorized_monthly_contribution',
            field=models.FloatField(default=0, verbose_name='Pre-Authorized Monthly Contribution'),
        ),
        migrations.AddField(
            model_name='investment',
            name='symbol',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Ticker Symbol'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='current_balance',
            field=models.FloatField(default=0, verbose_name='Current Balance'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk')], default=None, max_length=50, null=True, verbose_name='Risk Type'),
        ),
    ]
