# Generated by Django 3.1.2 on 2021-02-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0017_auto_20210216_0750"),
    ]

    operations = [
        migrations.RenameField(
            model_name="investment",
            old_name="principal_amount_invested",
            new_name="principal_investment_amount",
        ),
    ]
