# Generated by Django 3.1.2 on 2021-03-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0019_auto_20210220_0650"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialprofile",
            name="death_age",
            field=models.IntegerField(default=90, verbose_name="Death Age"),
        ),
        migrations.AddField(
            model_name="financialprofile",
            name="monthly_salary_before_tax",
            field=models.FloatField(
                default=80000, verbose_name="Monthly Salary Before Tax"
            ),
        ),
        migrations.AddField(
            model_name="financialprofile",
            name="percent_salary_for_spending",
            field=models.FloatField(
                default=25.0, verbose_name="Percent of Salary Allocated for Finances"
            ),
        ),
        migrations.AddField(
            model_name="financialprofile",
            name="province_of_residence",
            field=models.CharField(
                choices=[
                    ("AB", "Alberta"),
                    ("BC", "British Columbia"),
                    ("MB", "Manitoba"),
                    ("NB", "New Brunswick"),
                    ("NL", "Newfoundland and Labrador"),
                    ("NT", "Nunavut"),
                    ("ON", "Ontario"),
                    ("PEI", "Prince Edward Island"),
                    ("QB", "Quebec"),
                    ("SK", "Saskatchewan"),
                    ("YK", "Yukon"),
                ],
                default="AB",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="financialprofile",
            name="starting_rrsp_contribution_limit",
            field=models.FloatField(
                default=0, verbose_name="Remaining RRSP Contribution Limit"
            ),
        ),
        migrations.AddField(
            model_name="financialprofile",
            name="starting_tfsa_contribution_limit",
            field=models.FloatField(
                default=0, verbose_name="Remaining TFSA Contribution Limit"
            ),
        ),
    ]
