# Generated by Django 3.1.2 on 2021-03-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0020_auto_20210325_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialprofile',
            name='monthly_salary_before_tax',
            field=models.FloatField(default=8000, verbose_name='Monthly Salary Before Tax'),
        ),
    ]
