# Generated by Django 3.1.2 on 2021-03-25 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0021_auto_20210325_0212"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialprofile", name="monthly_allowance",
        ),
    ]
