# Generated by Django 3.1.2 on 2021-03-25 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finances", "0023_investment_account_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mortgage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "current_term_apr",
                    models.FloatField(
                        blank=True, default=None, null=True, verbose_name="APR"
                    ),
                ),
                (
                    "current_term_prime_modifier",
                    models.FloatField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Prime Modifier",
                    ),
                ),
                ("monthly_payment", models.FloatField(verbose_name="Monthly Payment")),
                (
                    "purchase_price",
                    models.FloatField(verbose_name="House Purchase Price"),
                ),
                ("purchase_date", models.DateField(verbose_name="Purchase Date")),
                ("downpayment_amount", models.FloatField(verbose_name="Downpayment")),
                (
                    "amortization_period_years",
                    models.FloatField(verbose_name="Amortization Period in Years"),
                ),
                (
                    "current_term_end_date",
                    models.DateField(verbose_name="Current Term End Date"),
                ),
                (
                    "current_term_start_date",
                    models.DateField(verbose_name="Current Term Start Date"),
                ),
                (
                    "current_term_interest_type",
                    models.DateField(verbose_name="Current Term Interest Type"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortgages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
