# Generated by Django 3.1.2 on 2021-03-26 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0025_auto_20210325_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mortgage',
            old_name='current_term_apr',
            new_name='apr',
        ),
        migrations.RenameField(
            model_name='mortgage',
            old_name='current_term_interest_type',
            new_name='interest_type',
        ),
        migrations.RenameField(
            model_name='mortgage',
            old_name='current_term_prime_modifier',
            new_name='prime_modifier',
        ),
    ]
