# Generated by Django 3.1.2 on 2021-03-30 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0027_delete_mortgage"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanInterest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest_type",
                    models.CharField(
                        choices=[
                            ("Fixed", "Fixed Interest Rate"),
                            ("Variable", "Variable Interest Rate"),
                        ],
                        default="Fixed",
                        max_length=50,
                    ),
                ),
                (
                    "apr",
                    models.FloatField(
                        blank=True, default=None, null=True, verbose_name="APR"
                    ),
                ),
                (
                    "prime_modifier",
                    models.FloatField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Prime Modifier",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_interest",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_interest",
                to="finances.loaninterest",
            ),
        ),
    ]
