# Generated by Django 3.1.2 on 2021-05-06 06:17

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0033_auto_20210506_0617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialprofile",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(1985, 1, 1, 0, 0), verbose_name="Birth Date"
            ),
        ),
    ]
