# Generated by Django 3.1.2 on 2021-05-14 06:39

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finances", "0034_auto_20210506_0617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialprofile",
            name="birth_date",
            field=models.DateField(
                default=datetime.date(1985, 1, 1), verbose_name="Birth Date"
            ),
        ),
        migrations.CreateModel(
            name="FinancialGoal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Nest Egg", "Nest Egg"),
                            ("Big Purchase", "Big Purchase"),
                        ],
                        default="Big Purchase",
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Amount to Save",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Date to Completion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
