# Generated by Django 3.1.2 on 2021-12-15 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0038_auto_20211215_0621"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="financial_data",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="finances.financialdata",
            ),
        ),
    ]
