# Generated by Django 3.1.2 on 2021-12-15 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finances", "0041_add_goals_to_financial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialdata",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_data",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="financialgoal",
            name="financial_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="finances.financialdata",
            ),
        ),
        migrations.AlterField(
            model_name="financialprofile",
            name="financial_data",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_profile",
                to="finances.financialdata",
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="financial_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investments",
                to="finances.financialdata",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="financial_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="finances.financialdata",
            ),
        ),
    ]
