# Generated by Django 3.1.2 on 2021-12-16 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0044_remove_users_from_financial_objects"),
    ]

    operations = [
        migrations.RemoveField(model_name="financialgoal", name="user",),
        migrations.RemoveField(model_name="financialprofile", name="user",),
        migrations.RemoveField(model_name="investment", name="user",),
        migrations.RemoveField(model_name="loan", name="user",),
    ]
