FROM node:10-alpine
WORKDIR /app

COPY ./frontend/package.json ./frontend/package-lock.json /app/
RUN npm install

COPY ./frontend/ /app/
RUN npm run build

EXPOSE 8000

CMD [ "npm", "run", "start" ]
