# Generated by Django 3.1.2 on 2021-10-17 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentpaymentplan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("free", "Limited Free Forever Plan"),
                    ("one-time", "One-Time Fee Plan"),
                    ("monthly", "Monthly Subscription Plan"),
                    ("annual", "Annual Subscription Plan"),
                    ("unlimited-freeUnlimited Free Plan", "Unlimited Free"),
                ],
                default="free",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="currentpaymentplan",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_access_plan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PaymentPlanIntent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_dt", models.DateTimeField(auto_created=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("free", "Limited Free Forever Plan"),
                            ("one-time", "One-Time Fee Plan"),
                            ("monthly", "Monthly Subscription Plan"),
                            ("annual", "Annual Subscription Plan"),
                            ("unlimited-freeUnlimited Free Plan", "Unlimited Free"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "payment_intent_id",
                    models.CharField(
                        max_length=225, verbose_name="Stripe Payment Intent ID"
                    ),
                ),
                (
                    "client_secret",
                    models.CharField(max_length=225, verbose_name="Client Secret"),
                ),
                (
                    "subscription_id",
                    models.CharField(
                        default=None,
                        max_length=225,
                        null=True,
                        verbose_name="Stripe Subscription ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_plan_intentions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
