# Generated by Django 3.1.2 on 2021-10-20 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0004_default_payment_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentpaymentplan",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_plan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paymentplanintent",
            name="created_dt",
            field=models.DateTimeField(verbose_name="Created Datetime"),
        ),
    ]
