# Generated by Django 3.1.2 on 2021-10-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_auto_20211020_0306"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentpaymentplan",
            name="subscription_id",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
