# Generated by Django 3.1.2 on 2021-10-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_currentpaymentplan_subscription_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentplanintent",
            name="subscription_id",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="currentpaymentplan",
            name="subscription_id",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
