# Generated by Django 3.1.2 on 2021-10-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_auto_20211021_0242"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentpaymentplan",
            name="is_cancelled",
            field=models.BooleanField(default=False, verbose_name="Is Plan Cancelled"),
        ),
    ]
