# Generated by Django 3.1.2 on 2021-12-16 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finances", "0045_auto_20211216_0603"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishedPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financial_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.financialdata",
                    ),
                ),
            ],
        ),
    ]
