# Generated by Django 3.1.2 on 2021-04-23 17:54

import hashid_field.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20210423_1724"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistuser",
            name="referral_id",
            field=hashid_field.field.HashidField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                blank=True,
                min_length=7,
                null=True,
                prefix="",
            ),
        ),
    ]
