# Generated by Django 3.1.2 on 2021-04-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_waitlistuser_referrer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistuser",
            name="first_name",
            field=models.CharField(
                default="first", max_length=30, verbose_name="First name"
            ),
        ),
    ]
