# Generated by Django 3.1.2 on 2021-04-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_waitlistuser_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waitlistuser",
            name="first_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="First name",
            ),
        ),
    ]
