# Generated by Django 3.1.2 on 2021-07-15 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20210709_1813"),
    ]

    operations = [
        migrations.RemoveField(model_name="waitlistuser", name="first_name",),
    ]
