# Generated by Django 3.1.2 on 2021-09-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_waitlistuser_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_id",
            field=models.CharField(
                default=None, null=True, max_length=50, verbose_name="Stripe ID"
            ),
        ),
    ]
